FROM python:3.9-slim-buster

WORKDIR /opt/app

COPY requirements.txt .
RUN pip install -r requirements_ui.txt
COPY streamlit_app.py ./

CMD ['streamlit', 'run', 'streamlit_app.py', '--server.port', '8000', '--server.address', '0.0.0.0']
