version: "2"

services:
  doc-equity:
    image: doc-equity:1.0
    container_name: doc_equity
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    command: [ "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "9000" ]
    volumes:
      - ./models/finetuned/:/opt/app/models/finetuned
      - ./upload:/opt/app/upload


  doc-equity-viz:
    image: doc-equity-ui:1.0
    container_name: doc_equity_ui
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "8000:8000"
    command: ['streamlit', 'run', 'streamlit_app.py', '--server.port', '8000', '--server.address', '0.0.0.0']
